#!/usr/bin/env bash
# This file is part of LINUX-TOOLS.
#
# LINUX-TOOLS is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# LINUX-TOOLS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with LINUX-TOOLS.  If not, see <http://www.gnu.org/licenses/gpl.txt>.
#
# If you need to develop a closed-source software, please contact us
# at 'social@itametis.com' to get a commercial version of LINUX-TOOLS,
# with a proprietary license instead.
#
########
#
# NOTE BENE :
# This script has been based on the work of another guy on the internet (but I can't remember who). As soon as I get the
# name of this guy, this header will be documented consequently.
#
########
#
# HOW TO INSTALL THIS SCRIPT ?
#
# 1) Add it under your PATH system
# 2) Create the environment variable MAVEN_HOME aiming the installation directory of Apache Maven (not the 'bin'/ subfolder,
#    just the root folder which contains the 'bin/' directory).
# 3) Restart your shell / X session and that's it.
#
# HOW TO CHOOSE MY COLOR ?
# The SED section call variables which are related to color. Just replace existing variable inside this part by the one
# related to the color you prefer.
#

mvn_color() {
    BOLD=`tput bold`
    UNDERLINE_ON=`tput smul`
    UNDERLINE_OFF=`tput rmul`
    TEXT_BLACK=`tput setaf 0`
    TEXT_RED=`tput setaf 1`
    TEXT_GREEN=`tput setaf 2`
    TEXT_YELLOW=`tput setaf 3`
    TEXT_BLUE=`tput setaf 4`
    TEXT_MAGENTA=`tput setaf 5`
    TEXT_CYAN=`tput setaf 6`
    TEXT_WHITE=`tput setaf 7`
    BACKGROUND_BLACK=`tput setab 0`
    BACKGROUND_RED=`tput setab 1`
    BACKGROUND_GREEN=`tput setab 2`
    BACKGROUND_YELLOW=`tput setab 3`
    BACKGROUND_BLUE=`tput setab 4`
    BACKGROUND_MAGENTA=`tput setab 5`
    BACKGROUND_CYAN=`tput setab 6`
    BACKGROUND_WHITE=`tput setab 7`
    RESET_FORMATTING=`tput sgr0`

    # Filter mvn output using sed
    ${MAVEN_HOME}/bin/mvn $@ | sed -e "s/\(\[INFO\]\)\(\ BUILD\ SUCCESS\)/${TEXT_BLUE}${BOLD}\1${TEXT_GREEN}\2${RESET_FORMATTING}/g" \
                    -e "s/\(\[INFO\]\)\(.*\)/${TEXT_BLUE}${BOLD}\1${TEXT_WHITE}\2/g" \
                    -e "s/\(\[WARNING\]\)\(.*\)/${BOLD}${TEXT_YELLOW}\1${TEXT_WHITE}\2${RESET_FORMATTING}/g" \
                    -e "s/\(\[ERROR\]\)\(.*\)/${BOLD}${TEXT_RED}\1${TEXT_WHITE}\2${RESET_FORMATTING}/g" \
                    -e "s/Tests run: \([^,]*\), Failures: \([^,]*\), Errors: \([^,]*\), Skipped: \([^,]*\)/${BOLD}${TEXT_GREEN}Tests run: \1${RESET_FORMATTING}, Failures: ${BOLD}${TEXT_RED}\2${RESET_FORMATTING}, Errors: ${BOLD}${TEXT_RED}\3${RESET_FORMATTING}, Skipped: ${BOLD}${TEXT_YELLOW}\4${RESET_FORMATTING}/g"

    # Make sure formatting is reset
    echo -ne ${RESET_FORMATTING}
}

# Override the mvn command with the colorized one.

mvn_color $*
